### ISSUE TITLE
BLAS documentation is out of date

### ISSUE THREAD

**Issue by carterbox** [conda-forge/blas-feedstock#139]
AFAICT, the [BLAS documentation in our knowledge base](https://conda-forge.org/docs/maintainer/knowledge_base/#blas) currently gives incorrect guidance on how to depend on BLAS.

![Image](https://github.com/user-attachments/assets/d3945f20-a7b7-4951-98e8-a9afa41783b9)

According to this guidance, the simplest way to depend on blas is to add the desired components to the host dependencies which will build against netlib:

```yaml
requirements:
  host:
    - libblas
    - libcblas
    - liblapack
    - liblapacke
```
However, this does not work because none of these packages will pull in header files, so the build will fail because it cannot include the BLAS headers.

Probably, the documentation should suggest something like:

```yaml
requirements:
  host:
    - blas-devel
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - nomkl  # maybe needed to prevent simultaneous install of netlib and mkl
```
but I'm actually not sure, because the following BLAS-specific build instructions have explicit run dependencies on each components.

```yaml
requirements:
  host:
    # Keep mkl-devel here for pinning
    - mkl-devel         {{ blas_impl == "mkl" }}
    - {{ blas_impl }}   {{ blas_impl != "mkl" }}
  run:
    - libblas * *{{ blas_impl }}
    - {{ blas_impl }}
```
which itself has errors and probably should be something like:

```yaml
requirements:
  host:
    # Keep mkl-devel here for pinning
    - mkl-devel         # [blas_impl == "mkl"]
    - {{ blas_impl }}
    - libblas * *{{ blas_impl }}
    # maybe needed to prevent simultaneous install of netlib and mkl?     
    - nomkl  # [blas_impl != "mkl"]
```
Where the selectors use the correct syntax and all of the packages are moved to host.
